INSERT INTO categories(name,slug,description) VALUES ('Berita BLC','berita-blc','Kabar lembaga'),('Kegiatan','kegiatan','Aktivitas pembelajaran'),('Tips Belajar','tips-belajar','Panduan belajar'),('Parenting','parenting','Wawasan keluarga'),('Prestasi','prestasi','Kabar pencapaian'),('Informasi Program','informasi-program','Informasi layanan');
INSERT INTO settings(`key`,value) VALUES ('site_name','Brainy Journal'),('site_description','Berita, Kegiatan, dan Inspirasi Belajar'),('institution_intro','Ruang informasi pendidikan. Profil lengkap lembaga perlu diisi oleh administrator.'),('contact_email',''),('contact_phone',''),('contact_address','');
-- Jalankan sesudah membuat admin; ganti @AUTHOR_ID dengan id pengguna tersebut.
SET @AUTHOR_ID=(SELECT id FROM users ORDER BY id LIMIT 1);
INSERT INTO posts(author_id,category_id,title,slug,excerpt,body,status) SELECT @AUTHOR_ID,id,'Contoh: Menyusun Rutinitas Belajar','contoh-rutinitas-belajar','Contoh konten—bukan publikasi resmi.','<p><strong>Contoh konten—bukan publikasi resmi.</strong></p><h2>Mulai secara realistis</h2><p>Susun waktu belajar yang mempertimbangkan kebutuhan setiap anak.</p>','draft' FROM categories WHERE slug='tips-belajar' AND @AUTHOR_ID IS NOT NULL;
INSERT INTO posts(author_id,category_id,title,slug,excerpt,body,status) SELECT @AUTHOR_ID,id,'Contoh: Catatan Kegiatan Kelas','contoh-kegiatan-kelas','Contoh konten—bukan publikasi resmi.','<p><strong>Contoh konten—bukan publikasi resmi.</strong></p><p>Gunakan artikel ini sebagai pola catatan kegiatan, bukan laporan acara nyata.</p>','draft' FROM categories WHERE slug='kegiatan' AND @AUTHOR_ID IS NOT NULL;
INSERT INTO posts(author_id,category_id,title,slug,excerpt,body,status) SELECT @AUTHOR_ID,id,'Contoh: Mendampingi Anak Bertanya','contoh-parenting-bertanya','Contoh konten—bukan publikasi resmi.','<p><strong>Contoh konten—bukan publikasi resmi.</strong></p><p>Berikan ruang aman untuk bertanya dan berdiskusi.</p>','draft' FROM categories WHERE slug='parenting' AND @AUTHOR_ID IS NOT NULL;
INSERT INTO posts(author_id,category_id,title,slug,excerpt,body,status) SELECT @AUTHOR_ID,id,'Contoh: Format Berita Lembaga','contoh-berita-lembaga','Contoh konten—bukan publikasi resmi.','<p><strong>Contoh konten—bukan publikasi resmi.</strong></p><p>Ganti seluruh isi dengan informasi yang telah diverifikasi.</p>','draft' FROM categories WHERE slug='berita-blc' AND @AUTHOR_ID IS NOT NULL;
INSERT INTO posts(author_id,category_id,title,slug,excerpt,body,status) SELECT @AUTHOR_ID,id,'Contoh: Mengapresiasi Proses','contoh-apresiasi-proses','Contoh konten—bukan publikasi resmi.','<p><strong>Contoh konten—bukan publikasi resmi.</strong></p><p>Hindari klaim pencapaian sebelum data tersedia.</p>','draft' FROM categories WHERE slug='prestasi' AND @AUTHOR_ID IS NOT NULL;
INSERT INTO posts(author_id,category_id,title,slug,excerpt,body,status) SELECT @AUTHOR_ID,id,'Contoh: Panduan Informasi Program','contoh-informasi-program','Contoh konten—bukan publikasi resmi.','<p><strong>Contoh konten—bukan publikasi resmi.</strong></p><p>Administrator perlu melengkapi rincian resmi program.</p>','draft' FROM categories WHERE slug='informasi-program' AND @AUTHOR_ID IS NOT NULL;
