<?php namespace App\Controllers;
final class PublicController{
 private function posts(string $where='1=1',array $params=[],int $page=1):array{$page=max(1,$page);$limit=9;$sql="SELECT p.*,c.name category,c.slug category_slug,u.name author,m.filename image,m.width image_width,m.height image_height FROM posts p JOIN categories c ON c.id=p.category_id JOIN users u ON u.id=p.author_id LEFT JOIN media m ON m.id=p.featured_media_id WHERE p.status='published' AND p.published_at<=UTC_TIMESTAMP() AND $where ORDER BY p.published_at DESC,p.id DESC LIMIT $limit OFFSET ".(($page-1)*$limit);$q=\db()->prepare($sql);$q->execute($params);return $q->fetchAll();}
 function home():void{$latest=$this->posts('1=1',[],1);$cats=\db()->query('SELECT name,slug FROM categories ORDER BY name')->fetchAll();\view('home',['title'=>'Beranda','posts'=>$latest,'featured'=>array_values(array_filter($latest,fn($p)=>$p['is_featured']))[0]??($latest[0]??null),'editor'=>array_slice(array_values(array_filter($latest,fn($p)=>$p['is_editor_pick'])),0,3),'categories'=>$cats]);}
 function index():void{\view('listing',['title'=>'Berita','posts'=>$this->posts('1=1',[],(int)($_GET['page']??1)),'page'=>max(1,(int)($_GET['page']??1))]);}
 function category(string $slug):void{$q=\db()->prepare('SELECT * FROM categories WHERE slug=?');$q->execute([$slug]);$c=$q->fetch();if(!$c){http_response_code(404);\view('404',['title'=>'Kategori tidak ditemukan']);return;}\view('listing',['title'=>$c['name'],'posts'=>$this->posts('p.category_id=?',[$c['id']],(int)($_GET['page']??1)),'page'=>max(1,(int)($_GET['page']??1))]);}
 function tag(string $slug):void{$q=\db()->prepare('SELECT * FROM tags WHERE slug=?');$q->execute([$slug]);$t=$q->fetch();if(!$t){http_response_code(404);\view('404',['title'=>'Tag tidak ditemukan']);return;}\view('listing',['title'=>'Tag: '.$t['name'],'posts'=>$this->posts('EXISTS(SELECT 1 FROM post_tags pt WHERE pt.post_id=p.id AND pt.tag_id=?)',[$t['id']],(int)($_GET['page']??1)),'page'=>max(1,(int)($_GET['page']??1))]);}
 function search():void{$term=mb_substr(trim((string)($_GET['q']??'')),0,100);$like='%'.$term.'%';$posts=$term===''?[]:$this->posts('(p.title LIKE ? OR p.excerpt LIKE ? OR p.body LIKE ?)',[$like,$like,$like],(int)($_GET['page']??1));\view('listing',['title'=>'Hasil pencarian','posts'=>$posts,'page'=>max(1,(int)($_GET['page']??1)),'query'=>$term,'noindex'=>true]);}
 function show(string $slug):void{$q=\db()->prepare("SELECT p.*,c.name category,c.slug category_slug,u.name author,m.filename image,m.width image_width,m.height image_height,m.caption FROM posts p JOIN categories c ON c.id=p.category_id JOIN users u ON u.id=p.author_id LEFT JOIN media m ON m.id=p.featured_media_id WHERE p.slug=? AND p.status='published' AND p.published_at<=UTC_TIMESTAMP()");$q->execute([$slug]);$post=$q->fetch();if(!$post){$r=\db()->prepare("SELECT p.slug FROM slug_redirects r JOIN posts p ON p.id=r.post_id WHERE r.old_slug=? AND p.status='published'");$r->execute([$slug]);if($new=$r->fetchColumn())\redirect('/berita/'.$new,301);http_response_code(404);\view('404',['title'=>'Artikel tidak ditemukan']);return;}$tags=\db()->prepare('SELECT t.* FROM tags t JOIN post_tags pt ON pt.tag_id=t.id WHERE pt.post_id=?');$tags->execute([$post['id']]);$related=$this->posts('p.id<>? AND p.category_id=?',[$post['id'],$post['category_id']],1);\view('post',['title'=>$post['meta_title']?:$post['title'],'description'=>$post['meta_description']?:$post['excerpt'],'post'=>$post,'tags'=>$tags->fetchAll(),'related'=>array_slice($related,0,3)]);}
 function page(string $slug,string $fallback):void{$q=\db()->prepare("SELECT * FROM pages WHERE slug=? AND status='published'");$q->execute([$slug]);$p=$q->fetch();\view('page',['title'=>$p['title']??$fallback,'body'=>$p['body']??'<p>Informasi ini belum dilengkapi oleh administrator.</p>']);}
 function sitemap():void{header('Content-Type: application/xml; charset=utf-8');$base=(require ROOT.'/config/app.php')['url'];$rows=\db()->query("SELECT slug,updated_at FROM posts WHERE status='published' AND published_at<=UTC_TIMESTAMP() ORDER BY id")->fetchAll();echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>'.\e($base).'</loc></url>';foreach($rows as $r)echo '<url><loc>'.\e($base.'/berita/'.rawurlencode($r['slug'])).'</loc><lastmod>'.date('c',strtotime($r['updated_at'])).'</lastmod></url>';echo '</urlset>';}
}
